name: CI/CD Pipeline - Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: BUILD (The Factory)
  build_and_push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pipeline-demo:latest

  # JOB 2: DEPLOY (The Delivery)
  deploy:
    name: Deploy to EC2
    needs: build_and_push  # Waits for Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Remote SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}      # Uses 3.236.242.7
          username: ${{ secrets.SSH_USER }}  # ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Pull the new image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/pipeline-demo:latest
            
            # 2. Stop old container (if any)
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            
            # 3. Run new container (Port 8080)
            sudo docker run -d --name my-app -p 8080:5000 ${{ secrets.DOCKER_USERNAME }}/pipeline-demo:latest